name: VC Issue 
run-name: Create Verifiable Credential 
on: [workflow_dispatch]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  CRED_DEF_ID: ${{ vars.CRED_DEF_ID }}
  HOLDER_HOST: ${{ vars.HOLDER_HOST }}
  ISSUER_HOST: ${{ vars.ISSUER_HOST }}

jobs:
  Build-Open-Faas-Fn-And-Create-VC:
    name: Build Open Faas Function and Create Verifiable Credential
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Docker
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      # semantic versioning
      - name: Get next version
        uses: reecetech/version-increment@2023.9.3
        id: version
        with:
          scheme: semver
          increment: patch
      - name: increase version in echo.yml
        run:  |
         sed -i 's|image: ghcr.io/martyk7/openfaas-fn:.*|image: ghcr.io/martyk7/openfaas-fn:${{ steps.version.outputs.version }}|' echo.yml
      - run: git tag ${{ steps.version.outputs.version }}
      - run: git push origin ${{ steps.version.outputs.version }}
      - uses: actions/setup-go@v5
        with:
         go-version: '>=1.17.0'
      - run: go version
      # Build and push
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: ${{ runner.os }}-buildx-
      - name: faas cli build
        run: |
          curl -sSL https://cli.openfaas.com | sh && \
          faas-cli template store pull golang-middleware && \
          FN_VERSION="${{ steps.version.outputs.version }}" && \
          faas-cli build -f echo.yml 
      - name: image push
        run: |
          IMAGE_NAME_LOWER=$(echo "${{ env.IMAGE_NAME }}" | tr '[:upper:]' '[:lower:]') && \
          docker push ${{ env.REGISTRY }}/${IMAGE_NAME_LOWER}:${{ steps.version.outputs.version }}

      # Create Verifiable Credential
      - name: set up nodejs to create Verifiable Credential 
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: install client and go
        run: |
          npm ci
          node holder-client.js ${{ env.HOLDER_HOST }} ${{ env.ISSUER_HOST }} ${{ env.CRED_DEF_ID }} ${{ env.IMAGE_NAME }} ${{ steps.version.outputs.version }} ${{ secrets.GITHUB_TOKEN }}


